version: "3.9"

services:
        web:
                build: WebSec-app/
                ports:
                        - "5000:5000"
                volumes:
                        - shared-volume:/var/shared-volume
        juice-shop:
                image: bkimminich/juice-shop
        proxy:
                build: Proxy-app/
                ports:
                        - "4000:4000"
                volumes:
                        - shared-volume:/var/shared-volume
                depends_on:
                        - "web"

volumes:
        shared-volume:
                external: false

