FROM python:3.7-alpine
WORKDIR /code
ENV FLASK_APP=proxyapp.py
ENV FLASK_RUN_HOST=0.0.0.0
RUN apk add --no-cache gcc musl-dev linux-headers
COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt
EXPOSE 4000
COPY . .
CMD ["flask", "run", "-p", "4000"]

